# JoinSystem Configuration
# {player} = the PlayerName who Joined\Left
# ==============================================================================
JoinMessage: "§7[§a+§7] {player}"
LeaveMessage: "§7[§c-§7] {player}"
